### ISSUE TITLE
After the character Ai reply 3 to 5 time i get this error.....

### ISSUE THREAD

**Issue by xamuel** [niizam/tcharai#2]
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    curses.wrapper(run)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "test.py", line 33, in run
    stdscr.addstr(time_str+ chara_name + ' ✉\n' + output_text + '\n \n')
_curses.error: addwstr() returned ERR

It crashed, after re-run the script it can still work, i tested on the browser version of character AI don't have it this issue, seem like not character AI filter issue...

**Comment by Imloopdev** [comment]
Im getting the same issue, any fix?
